In [1]:
pip install numpy scipy scikit-learn

   ---------------------------------------- 0.0/39.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/39.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/39.4 MB ? eta -:--:--
   - -------------------------------------- 1.3/39.4 MB 4.5 MB/s eta 0:00:09
   -- ------------------------------------- 2.1/39.4 MB 4.2 MB/s eta 0:00:09
   --- ------------------------------------ 3.1/39.4 MB 4.3 MB/s eta 0:00:09
   ---- ----------------------------------- 4.7/39.4 MB 5.2 MB/s eta 0:00:07
   ------ --------------------------------- 6.3/39.4 MB 5.6 MB/s eta 0:00:06
   ------- -------------------------------- 7.3/39.4 MB 5.7 MB/s eta 0:00:06
   -------- ------------------------------- 8.4/39.4 MB 5.6 MB/s eta 0:00:06
   --------- ------------------------------ 9.2/39.4 MB 5.4 MB/s eta 0:00:06
   ---------- ----------------------------- 10.5/39.4 MB 5.5 MB/s eta 0:00:06
   ----------- ---------------------------- 11.8/39.4 MB 5.5 MB/s eta 0:00:05
   ------------- -

In [1]:
from sklearn.datasets import load_iris 
iris = load_iris() 

X = iris.data 
y = iris.target 
  
feature_names = iris.feature_names 
target_names = iris.target_names 
  
print("Feature names:", feature_names) 
print("Target names:", target_names) 

print("\nType of X is:", type(X)) 

print("\nFirst 5 rows of X:\n", X[:5])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

Type of X is: <class 'numpy.ndarray'>

First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
