In [8]:
pip install scipy numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
'''
constants in Scipy
'''
from scipy import constants

print(constants.liter)
print(constants.pi)
print(dir(constants))

0.001
3.141592653589793
['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'g

In [5]:
'''
Metric Preferences....
'''
print(constants.zetta)
print(constants.zepto)

1e+21
1e-21


In [6]:
'''
Binary Prefernces.....
'''
print(constants.kibi)
print(constants.mebi)

1024
1048576


In [7]:
'''
Mass Values....
'''
print(constants.metric_ton)
print(constants.gram)

1000.0
0.001


In [12]:
import numpy as np

a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
print(a,a.ndim)
print(b,b.ndim)
print(c,c.ndim)


[1 2 3] 1
[[1 2 3]
 [4 5 6]] 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 3


In [13]:
'''
Arange Function in Numpy
'''
d=np.arange(1,10) # Using Start and Stop value
e=np.arange(3.0) # Using Stop value
f=np.arange(20,dtype="float") # Using stop value with datatype
g=np.arange(2,20,2) #Using Step with Start and Stop Value.
print(d)
print(e)
print(f)
print(g)

[1 2 3 4 5 6 7 8 9]
[0. 1. 2.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
[ 2  4  6  8 10 12 14 16 18]


In [ ]:
'''
Zeros Function
'''
num1=np.zeros(5) #One Dimensional Array
num2=np.zeros(10, dtype=int) #One Dimension with dtype
num3=np.zeros([2,3]) #Two Dimensional Array
print(num1)
print(num2)
print(num3)

[0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
'''
Ones Function
'''
num4=np.ones(5)
num5=np.ones(10,dtype=int)
num6=np.ones([1,2])
print(num4)
print(num5)
print(num6)

[1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[[1. 1.]]


In [22]:
'''
Empty Function
'''
num8=np.empty(7)
num9=np.empty(10,dtype=int)
print(num8)
print(num9)

[3.47739835e-081 6.64024228e-321 0.00000000e+000 1.01306022e-311
 0.00000000e+000 3.25060610e-319 6.95174042e-310]
[      2050536304488                  36                   0
                   0                   0 3762306900297343330
 3761681287528984877 3258693204281472825 3559588877022935350
          1714971442]


In [29]:
'''
Linspace Function......
'''
num10=np.linspace(1,100,num=5)
num11=np.linspace(1,100,num=5,endpoint=False)
num12=np.linspace(1,100,num=5,retstep=True)
num13=np.linspace(1,100,num=5,dtype=int)
print(num10)
print(num11)
print(num12)
print(num13)

[  1.    25.75  50.5   75.25 100.  ]
[ 1.  20.8 40.6 60.4 80.2]
(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), np.float64(24.75))
[  1  25  50  75 100]


In [31]:
num14=np.random.rand(5)
num15=np.random.rand(3,2)
print(num14)
print(num15)

[0.99892266 0.8904206  0.26239212 0.93970553 0.953858  ]
[[0.50436893 0.45756831]
 [0.38497082 0.36615147]
 [0.54453416 0.81470766]]


In [32]:
np.random.randn(3)

array([ 0.57229725,  0.57641398, -0.30518084])

In [33]:
np.random.ranf(5)

array([0.56881918, 0.07766312, 0.94633997, 0.78943502, 0.9812138 ])

In [35]:
np.random.randint(5,size=10)

array([3, 1, 4, 3, 0, 1, 0, 2, 3, 0], dtype=int32)

In [38]:
np.random.randint(3,size=(4,2))

array([[2, 2],
       [2, 1],
       [0, 1],
       [0, 0]], dtype=int32)