In [1]:
import numpy as np

In [3]:
a=np.arange(1,10)
index=np.array([1,4,5])
print(a[index])

[2 5 6]


In [5]:
b=np.array(
    [
        [1,2,3],[4,5,6],[7,8,9]
    ]
)
b[[0,2],[2,0]]

array([3, 7])

In [8]:
c=np.array([1,2,-4,5,-10])
print(c[c<0]*2)
print(c[c>0])

[ -8 -20]
[1 2 5]
