In [2]:
import numpy as np

In [3]:
a=np.array(
    [1,2,3,4,5]
)
print(a[0])

1


In [ ]:
b=np.array(
    [
        [1,2],
        [3,4],
        [5,6]
    ]
)

print(b[1][1])

4


In [8]:
c=[[[1,2,3,4],[5,6,7,8],[9,20,11,22]],[[10,12,14,15],[16,17,18,19],[21,23,24,25]]]
d=np.array(c)
print(d)
print(d[1][2][2])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 20 11 22]]

 [[10 12 14 15]
  [16 17 18 19]
  [21 23 24 25]]]
24


In [12]:
e=np.array([1,2,3,4,5])
print(e[2:])
print(e[:2])
print(e[::2])

[3 4 5]
[1 2]
[1 3 5]


In [15]:
f=np.array(
    [
        [1,2],
        [3,4],
        [5,6]
    ]
)
print(f[1:,1:])

[[4]
 [6]]


In [31]:
n=np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)
print(n)
print(n[:,:1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [5]
 [9]]


In [33]:
h=[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]
i=np.array(h)
print(i)
print(i[:,:,0:1])
print(i[:,1:,::2])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]
[[[ 5  7]
  [ 9 11]]

 [[17 19]
  [21 23]]]
