In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a.ndim)
print(a)

1
[1 2 3 4]


In [10]:
b=np.zeros(5)
print(b)
print(b.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
n=np.array(
    [
        [1,2],
        [3,4]
    ]
)
print(n.ndim)

2


In [6]:
print(n.dtype)

int64


In [7]:
print(n.itemsize)

8


In [9]:
c=np.array(
    [1,2,3,4],dtype=np.int8
)
print(c,c.dtype)

[1 2 3 4] int8


In [21]:
g=np.array(
    [1,2,3,4],dtype='f'
)
print(g)
# g.astype(int)
# print(g)


[1. 2. 3. 4.]
